name: Tests

on:
    pull_request:
    push:
        branches:
        - master

jobs:
  build:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        resolver:
        - nightly
        - lts-23
        - lts-22
        - lts-20
        - lts-18
        - lts-16
        - lts-14
        exclude:
          # No setup information found for ghc-8.6.5 on your platform. This probably means a GHC binary distribution has not yet been added for OS key macosx-aarch64.
          - os: macos-latest
            resolver: lts-14
          # No setup information found for ghc-8.8.4 on your platform. This probably means a GHC binary distribution has not yet been added for OS key macosx-aarch64.
          - os: macos-latest
            resolver: lts-16
          # Warning: Couldn't figure out LLVM version!
          # Make sure you have installed LLVM between [9 and 13)
          # ghc: could not execute: opt
          - os: macos-latest
            resolver: lts-18

    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'
          stack-no-global: true
      - name: Build and run tests
        shell: bash
        run: |
            set -ex
            # stack upgrade --force-download
            stack --version
            stack test --fast --no-terminal --resolver=${{ matrix.resolver }}
