name: Tests

on:
    pull_request:
    push:
        branches:
        - master

jobs:
  build:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        resolver:
        - nightly
        - lts-18
        - lts-16
        - lts-14

    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Build and run tests
        shell: bash
        run: |
            set -ex
            stack upgrade --force-download
            stack --version
            stack test --fast --no-terminal --resolver=${{ matrix.resolver }}
